version: '3'
services:
  vpn_socks_proxy:
    build:
      dockerfile: Dockerfile
    container_name: vpn-socks-proxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - WORKING_DIR=/openvpn/pia
      - FILTER=ca_*
      - USERNAME=PIA-USERNAME
      - PASSWORD=PIA-PASSWORD
    networks:
      - vpn_socks_proxy
    ports:
      - 1080:1080
    restart: always

networks:
  vpn_socks_proxy:
