version: '3'
services:
  vpn_socks_proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpn-socks-proxy
    image: ghcr.io/ivanjosipovic/vpn-socks-proxy/vpn-socks-proxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - CONFIG1=/openvpn/pia/ca_vancouver.ovpn
      - FILTER=/openvpn/pia/ca_
      - SHUFFLE=YES
      - USERNAME=PIA-USERNAME
      - PASSWORD=PIA-PASSWORD
    networks:
      - vpn_socks_proxy
    ports:
      - 1080:1080
    restart: always

networks:
  vpn_socks_proxy:
