#!/bin/sh
set -e -u -o pipefail

if [ $FILTER != "" ]; then
	if [ $SHUFFLE == "YES" ]; then
	echo "Filter/Shuffle: $FILTER";
		CONFIG=$(ls $FILTER* | shuf | head -1)
	else
		echo "Filter: $FILTER";
		CONFIG=$(ls $FILTER* | head -1)
	fi
fi

set -- "$@" '--config' "${CONFIG}"

echo "Config: $CONFIG"

if [ -n "$USERNAME" -a -n "$PASSWORD" ]; then
	echo "$USERNAME" > /openvpn/auth.conf
	echo "$PASSWORD" >> /openvpn/auth.conf
	chmod 400 /openvpn/auth.conf
	set -- "$@" '--auth-user-pass' '/openvpn/auth.conf'
else
	echo "OpenVPN credentials not set. Exiting."
	exit 1
fi

openvpn "$@" --user nobody --auth-nocache --script-security 2 --up "/app/init.sh"