#!/bin/sh
set -e -u -o pipefail

if [ $FILTER != "" ]; then
	echo "Filter: '$FILTER'"
	CONFIG=$(find $WORKING_DIR -type f -name $FILTER | shuf | tail -n 1)
fi

echo "Config: $CONFIG"

set -- "$@" '--config' "${CONFIG}"

if [ -n "$USERNAME" -a -n "$PASSWORD" ]; then
	echo "$USERNAME" > /openvpn/auth.conf
	echo "$PASSWORD" >> /openvpn/auth.conf
	chmod 400 /openvpn/auth.conf
	set -- "$@" '--auth-user-pass' '/openvpn/auth.conf'
else
	echo "OpenVPN credentials not set. Exiting."
	exit 1
fi

cd $WORKING_DIR
echo "Startin VPN"
echo ""
openvpn "$@" --auth-nocache --script-security 2 --up "/app/init.sh" --down "/app/down.sh" --connect-retry-max 2
